# ruff is used for autoformatting and linting Python code
#
# ref: https://docs.astral.sh/ruff/configuration/
#
[tool.ruff]
target-version = "py38"

# ruff formatter ref: https://docs.astral.sh/ruff/formatter/
[tool.ruff.format]
quote-style = "preserve"

# ruff linter ref: https://docs.astral.sh/ruff/linter/
[tool.ruff.lint]
ignore = []
select = [
    "E9", # pycodestyle
    "I",  # isort
    "UP", # pyupgrade
    "F",  # flake8, autoflake
]
